version: "3"

services:
  app:
    container_name: csv-profile-service
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "5001:8080"
    volumes:
      - .:/www/deno/app
    command: deno task dev
    restart: always
    depends_on:
      - db
      - localstack

  db:
    container_name: db-csv-profile
    build: .docker/mysql
    tty: true
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=p@a55w0rd
      - MYSQL_ROOT_PASSWORD=p@a55w0rd
      - MYSQL_DATABASE=csvprofile
    volumes:
      - .docker/dbdata:/var/www/html

  localstack:
    container_name: aws-localstack
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=sa-east-1
      - PORT_WEB_UI=8082
      - HOSTNAME_EXTERNAL=localhost
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - DEFAULT_REGION=sa-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SREVICES=s3,sns,sqs,ses
      - EDGE_PORT=4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db-data: {}